// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAb3P_DG7ba5M63VsdD3uetLxwzzUGIUAI',
    appId: '1:235276295895:web:5569e0bbcde25192649a92',
    messagingSenderId: '235276295895',
    projectId: 'presence-c317d',
    authDomain: 'presence-c317d.firebaseapp.com',
    databaseURL: 'https://presence-c317d-default-rtdb.firebaseio.com',
    storageBucket: 'presence-c317d.firebasestorage.app',
    measurementId: 'G-76HFTC5H9K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFMz0WMQrBreRSJd5nwA-BZt_h6hLErWI',
    appId: '1:235276295895:android:058aec4e606f2a35649a92',
    messagingSenderId: '235276295895',
    projectId: 'presence-c317d',
    databaseURL: 'https://presence-c317d-default-rtdb.firebaseio.com',
    storageBucket: 'presence-c317d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDs5RmSnL-Otyl68v8-NPHs3QazqsKDopA',
    appId: '1:235276295895:ios:bc1bc0d640fe4c74649a92',
    messagingSenderId: '235276295895',
    projectId: 'presence-c317d',
    databaseURL: 'https://presence-c317d-default-rtdb.firebaseio.com',
    storageBucket: 'presence-c317d.firebasestorage.app',
    iosBundleId: 'com.example.projetPresence',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDs5RmSnL-Otyl68v8-NPHs3QazqsKDopA',
    appId: '1:235276295895:ios:bc1bc0d640fe4c74649a92',
    messagingSenderId: '235276295895',
    projectId: 'presence-c317d',
    databaseURL: 'https://presence-c317d-default-rtdb.firebaseio.com',
    storageBucket: 'presence-c317d.firebasestorage.app',
    iosBundleId: 'com.example.projetPresence',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnwoiptD_ef-al04PQv3bQFhPfj8RhL_0',
    appId: '1:235276295895:web:4cd6fafb49ab3478649a92',
    messagingSenderId: '235276295895',
    projectId: 'presence-c317d',
    authDomain: 'presence-c317d.firebaseapp.com',
    databaseURL: 'https://presence-c317d-default-rtdb.firebaseio.com',
    storageBucket: 'presence-c317d.firebasestorage.app',
    measurementId: 'G-K7NX8GHG1V',
  );
}
